name: Call AI API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-ai-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run AI API script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python scripts/ai_script.py
