name: Daily Reminders

on:
  schedule:
    # Run at 9:00 AM and 10:00 PM (UTC+8)
    - cron: '0 1 * * *'  # 9:00 AM UTC+8 = 1:00 AM UTC
    - cron: '0 14 * * *' # 10:00 PM UTC+8 = 2:00 PM UTC
  workflow_dispatch:
    inputs:
      message_type:
        description: 'Type of message to send'
        required: true
        default: 'morning'
        type: choice
        options:
          - morning
          - evening

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Determine message type
        id: determine_type
        run: |
          # 对于手动触发，使用输入参数
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "type=${{ inputs.message_type }}" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # 对于定时触发，检查当前时间（UTC+8）
          HOUR=$(TZ='Asia/Shanghai' date +%H)
          echo "Current hour in Shanghai: $HOUR"
          
          if [ $HOUR -eq 9 ] || [ $HOUR -eq 8 ] || [ $HOUR -eq 10 ]; then
            echo "type=morning" >> $GITHUB_OUTPUT
          elif [ $HOUR -eq 22 ] || [ $HOUR -eq 21 ] || [ $HOUR -eq 23 ]; then
            echo "type=evening" >> $GITHUB_OUTPUT
          else
            echo "Not sending a message at hour $HOUR"
            echo "type=none" >> $GITHUB_OUTPUT
          fi

      - name: Send reminder
        if: steps.determine_type.outputs.type != 'none'
        env:
          WEBHOOK_KEY: ${{ secrets.WEBHOOK_KEY }}
          API_KEY: ${{ secrets.API_KEY }}  # 使用 API_KEY
          MESSAGE_TYPE: ${{ steps.determine_type.outputs.type }}
        run: python scripts/send_reminder.py